### ISSUE TITLE
Cannot find DirectFB2 backend on GTK3

### ISSUE THREAD

**Issue by shezw** [directfb2/directfb2.github.io#1]
The introduction on [directfb](https://directfb2.github.io/#gtk) show me DFB2 is supporting GTK3.
But I can't find any 'directfb' file in any of gtk+-3 packages.
How can I compile a gtk-directfb-3.0 lib?

**Comment by caramelli** [comment]
Yes, you can get a patch from the original site archive: https://web.archive.org/web/20150429225234/http://directfb.org/downloads/Libs/gtk-directfb-3-12-20140731.patch

It's a bit old, it can be tricky to properly build GTK+ 3 to work with DirectFB: it would be easier if a DirectFB backend was maintained directly in GTK (like with GTK+ 2 in the past).

I'm hoping to see a DirectFB port in GTK 4, it's on my TODO list, and any help making it is welcome!

**Comment by shezw** [comment]
Hi, caramelli
Your suggestion works for me, thank you so much.
It is also worked on gtk+-3.22.30.
